/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.edusys.ui;

import com.edusys.dao.NhanVienDAO;
import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DoiMatKhauDialog extends javax.swing.JDialog {

    /**
     * Creates new form DoiMatKhauDialog
     */
    NhanVienDAO dao = new NhanVienDAO();

    public DoiMatKhauDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        inti();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        btnDoiMatKhau = new javax.swing.JButton();
        btnHuyBo = new javax.swing.JButton();
        txtMatKhauHienTai = new javax.swing.JPasswordField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtMatKhauMoi2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đổi Mật Khẩu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 236, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Tên Đăng Nhập ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 108, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Mật Khẩu Mới");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, 117, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Mật Khẩu Hiện Tại");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Xác Nhập Mật Khẩu Mới");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 186, -1));
        getContentPane().add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 182, -1));

        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/Hinh/Refresh.png"))); // NOI18N
        btnDoiMatKhau.setText("Đồng Ý");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        btnHuyBo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/Hinh/No.png"))); // NOI18N
        btnHuyBo.setText("Hủy Bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });
        getContentPane().add(btnHuyBo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 110, -1));
        getContentPane().add(txtMatKhauHienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 223, -1));
        getContentPane().add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 263, 182, -1));
        getContentPane().add(txtMatKhauMoi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 223, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/Hinh/hinh-anh-dong-de-thuong (1).gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        // TODO add your handling code here:
        huyBo();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
        doiMatKhau();
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiMatKhauDialog dialog = new DoiMatKhauDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhauHienTai;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtMatKhauMoi2;
    // End of variables declaration//GEN-END:variables
private void huyBo() {
        this.dispose();
    }

    void inti() {
//        txtMaNV.setText(Auth.user.getMaNV());
        setLocationRelativeTo(null);
    }

//    private void doiMatKhau() {
//        //txtMaNV.setText(Auth.user.getMaNV());
//        String manv = txtMaNV.getText();
//        String matKhau = new String(txtMatKhauHienTai.getPassword());
//        String matKhauMoi = new String(txtMatKhauMoi.getPassword());
//        String matKhauMoi2 = new String(txtMatKhauMoi2.getPassword());
//        if (!manv.equalsIgnoreCase(Auth.user.getMaNV())) {
//            MsgBox.alert(this, "Sai tên đăng nhập");
//
//        } else if (!matKhau.equals(Auth.user.getMatKhau())) {
//            MsgBox.alert(this, "Sai mật khẩu");
//
//        } else if (!matKhauMoi.equals(matKhauMoi2)) {
//            MsgBox.alert(this, "Sát nhận mật khẩu không đúng");
//
//        } else {
//            Auth.user.setMatKhau(matKhauMoi);
//            dao.update(Auth.user);
//            MsgBox.alert(this, "Đổi mật khẩu thành công");
//        }
//
//    }
    private void doiMatKhau() {
        if (checkValidate()) {
            String manv = txtMaNV.getText();
            String matKhau = new String(txtMatKhauHienTai.getPassword());
            String matKhauMoi = new String(txtMatKhauMoi.getPassword());
            String xacNhanMatKhau = new String(txtMatKhauMoi2.getPassword());
            if (!manv.equalsIgnoreCase(Auth.user.getMaNV())) {
                MsgBox.alert(this, "Sai tên đăng nhập!");
            } else if (!matKhau.equals(Auth.user.getMatKhau())) {
                MsgBox.alert(this, "Sai mật khẩu!");
            } else if (!matKhauMoi.equals(xacNhanMatKhau)) {
                MsgBox.alert(this, "xác nhận mật khẩu không đúng!");
            } else {
                Auth.user.setMatKhau(matKhauMoi);
                dao.update(Auth.user);
                MsgBox.alert(this, "Đổi mật khẩu thành công!");
                this.dispose();
            }
        }
    }

    public boolean checkValidate() {

        if (txtMaNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã Nhân Viên ", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtMaNV.requestFocus();
            return false;
        }
        String passWord = new String(txtMatKhauHienTai.getPassword());
        String passWord2 = new String(txtMatKhauMoi.getPassword());
        String passWord3 = new String(txtMatKhauMoi2.getPassword());
        if (txtMatKhauHienTai.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mật Khẩu!", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtMatKhauHienTai.requestFocus();
            return false;
        }

        if (txtMatKhauMoi.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mật Khẩu Mới", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtMatKhauMoi.requestFocus();
            return false;
        }
        if (txtMatKhauMoi2.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập lại Mật Khẩu Mới", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtMatKhauMoi2.requestFocus();
            return false;
        }
        return true;
    }
}
